routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::group(['middleware' => ['auth:sanctum']], function() {
    Route::resources([
        'users' => 'App\Http\Controllers\UserController',
        'departments' => 'App\Http\Controllers\DepartmentController',
        'sge_types' => 'App\Http\Controllers\SGETypesController',
        'sge_classes' => 'App\Http\Controllers\SGEClassController',
        'sge_students' => 'App\Http\Controllers\SGEStudentController',
        'students' => 'App\Http\Controllers\StudentController',
        'programs' => 'App\Http\Controllers\CourseController',
    ]);

    Route::get('students/export/{id}', 'App\Http\Controllers\StudentController@export')->name('students.export');
});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Sanctum\HasApiTokens;
use Laravel\Scout\Searchable;

class User extends Authenticatable
{
    use Searchable;
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use Notifiable;
    use TwoFactorAuthenticatable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = [];
    protected $table = "users";

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'profile_photo_url',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('users.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = User::create($request->all());
        if($request->has('password')){
            $user->password = Hash::make($request->password);
            $user->save();
        }
        return redirect()->route('users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('users.edit',compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $user->fill($request->except('password'))->save();
        if($request->has('password')){
            $user->password = Hash::make($request->password);
            $user->save();
        }
        return redirect()->route('users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();
        return redirect()->route('users.index');
    }
}

app/Http/Livewire/UserTable.php
<?php

namespace App\Http\Livewire;

use App\Models\User;
use Livewire\Component;
use Livewire\WithPagination;

class UserTable extends Component
{
    use WithPagination;

    protected $users;
    public $search = null;

    public function updating()
    {
        $this->resetPage();
    }

    public function updated()
    {
        $this->resetPage();
    }

    public function render()
    {
        $this->users = is_null($this->search) || $this->search == '' ? User::orderBy('role')->paginate(5) : User::search($this->search)->orderBy('role')->paginate(5);
        return view('livewire.user-table', [
            'users' => $this->users,
        ]);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/users/create.blade.php
<x-app-layout>
    <div class="py-12">
        <div class="max-w-md mx-auto border-4 shadow-xl bg-white/90 border-amber-300/50 sm:rounded-lg sm:p-6 lg:p-6">
                <x-jet-validation-errors class="mb-4" />
                <div class="top-0 left-0 flex items-end justify-end py-2">
                    <a href="{{url()->previous()}}" class="hidden text-gray-600 cursor-pointer md:block focus:outline-none">
                        <i class="text-md fas fa-times"></i>
                    </a>
                </div>
                <form method="POST" action="{{ route('users.store') }}">
                    @csrf

                    <div>
                        <x-jet-label for="role" value="{{ __('User Role') }}" />
                        <select id="role" class="block w-full mt-1 border-gray-300 rounded-md shadow-sm focus:border-amber-300 focus:ring focus:ring-amber-300/50" name="role" required autofocus>
                            <option value="0">Admin</option>
                            <option value="1">ICEP Director</option>
                            <option value="2">ILRAD Director</option>
                            <option value="3">Dean</option>
                            <option value="4">Staff</option>
                        </select>
                    </div>

                    <div class="mt-4">
                        <x-jet-label for="name" value="{{ __('Name') }}" />
                        <x-jet-input id="name" class="block w-full mt-1" type="text" name="name" :value="old('name')" required autofocus autocomplete="name" />
                    </div>

                    <div class="mt-4">
                        <x-jet-label for="email" value="{{ __('Email') }}" />
                        <x-jet-input id="email" class="block w-full mt-1" type="email" name="email" :value="old('email')" required />
                    </div>

                    <div class="mt-4">
                        <x-jet-label for="password" value="{{ __('Password') }}" />
                        <x-jet-input id="password" class="block w-full mt-1" type="password" name="password" required autocomplete="new-password" />
                    </div>

                    <div class="flex items-center justify-end mt-4">
                        <x-jet-button class="w-full">
                            CREATE USER
                        </x-jet-button>
                    </div>
                </form>
        </div>
    </div>
</x-app-layout>

resources/views/users/edit.blade.php
<x-app-layout>
    <div class="py-12">
        <div class="max-w-md p-6 mx-auto border-4 shadow-xl bg-white/90 border-amber-300/50 sm:rounded-lg">
            <x-jet-validation-errors class="mb-4" />
            <div class="top-0 left-0 flex items-end justify-end py-2">
                <a href="{{url()->previous()}}" class="hidden text-gray-600 cursor-pointer md:block focus:outline-none">
                    <i class="text-md fas fa-times"></i>
                </a>
            </div>
            <form method="POST" action="{{ route('users.update',$user->id) }}">
                @method('patch')
                @csrf

                <div>
                    <x-jet-label for="role" value="{{ __('User Role') }}" />
                    <select id="role" class="block w-full mt-1 border-gray-300 rounded-md shadow-sm focus:border-amber-300 focus:ring focus:ring-amber-300/50" name="role" required autofocus>
                        <option value="0" {{ $user->role == 0 ? 'selected' : '' }}>Admin</option>
                        <option value="1" {{ $user->role == 1 ? 'selected' : '' }}>ICEP Director</option>
                        <option value="2" {{ $user->role == 2 ? 'selected' : '' }}>ILRAD Director</option>
                        <option value="3" {{ $user->role == 3 ? 'selected' : '' }}>Dean</option>
                        <option value="4" {{ $user->role == 4 ? 'selected' : '' }}>Staff</option>
                    </select>
                </div>

                <div class="mt-4">
                    <x-jet-label for="name" value="{{ __('Name') }}" />
                    <x-jet-input id="name" class="block w-full mt-1" type="text" name="name" value="{{ $user->name }}" required autofocus autocomplete="name" />
                </div>

                <div class="mt-4">
                    <x-jet-label for="email" value="{{ __('Email') }}" />
                    <x-jet-input id="email" class="block w-full mt-1" type="email" name="email" value="{{ $user->email }}" required />
                </div>

                <div class="mt-4">
                    <x-jet-label for="password" value="{{ __('Password') }}" />
                    <x-jet-input id="password" class="block w-full mt-1" type="password" name="password" value="{{ $user->password }}" required autocomplete="new-password" />
                </div>

                <div class="flex items-center justify-center mt-4">
                    <x-jet-button class="w-full">
                        UPDATE USER
                    </x-jet-button>
                </div>
            </form>
        </div>
    </div>
</x-app-layout>

resources/views/users/index.blade.php
<x-app-layout>
    <div class="py-12">
        <div class="mx-auto max-w-7xl sm:px-6 lg:px-8">
            @livewire('user-table')
        </div>
    </div>
</x-app-layout>