routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::group(['middleware' => ['auth:sanctum']], function() {
    Route::resources([
        'users' => 'App\Http\Controllers\UserController',
        'departments' => 'App\Http\Controllers\DepartmentController',
        'sge_types' => 'App\Http\Controllers\SGETypesController',
        'sge_classes' => 'App\Http\Controllers\SGEClassController',
        'sge_students' => 'App\Http\Controllers\SGEStudentController',
        'students' => 'App\Http\Controllers\StudentController',
        'programs' => 'App\Http\Controllers\CourseController',
    ]);

    Route::get('students/export/{id}', 'App\Http\Controllers\StudentController@export')->name('students.export');
});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

app/Http/Livewire/ClasslistTable.php
<?php

namespace App\Http\Livewire;

use App\Models\SGEStudent;
use App\Models\SGEClass;
use App\Models\SGETypes;
use Livewire\Component;
use Livewire\WithPagination;

class ClasslistTable extends Component
{
    use WithPagination;

    protected $sge_classes;
    public $sge_types, $students;
    public $search = null;

    public function mount(SGETypes $sge_types, SGEStudent $students)
    {
        $this->students = $students->all();
        $this->sge_types = $sge_types->all();
    }

    public function updating()
    {
        $this->resetPage();
    }

    public function updated()
    {
        $this->resetPage();
    }

    public function render()
    {
        $this->sge_classes = is_null($this->search) || $this->search == '' ? SGEClass::orderBy('created_at')->paginate(5) : SGEClass::search($this->search)->orderBy('created_at')->paginate(5);
        return view('livewire.classlist-table', [
            'sge_classes' => $this->sge_classes,
        ]);
    }
}

app/Http/Livewire/Dashboard.php
<?php

namespace App\Http\Livewire;

use App\Models\User;
use App\Models\Student;
use App\Models\Course;
use App\Models\Department;
use App\Models\SGETypes;
use App\Models\SGEClass;
use App\Models\SGEStudent;
use Livewire\Component;

class Dashboard extends Component
{
    public $users;
    public $students;
    public $courses;
    public $departments;
    public $classlists;
    public $sgetypes;
    public $total_students;
    public $ctrStudentsPerType = array();
    public $ctrIP = array();
    public $ctrComplete = array();

    public function mount(User $users, Department $departments, SGEClass $classlists, SGEStudent $students, Course $courses, SGETypes $sgetypes, Student $total_students){
        $this->users = $users->all();
        $this->departments = $departments->all();
        $this->classlists = $classlists->all();
        
        $this->total_students = $total_students->all();
        $this->students = $students->all();
        $this->courses = $courses->all();
        $this->sgetypes = $sgetypes->all();

        foreach($this->sgetypes as $sgetype)
        {
            array_push($this->ctrStudentsPerType, SGEStudent::where('type_id',$sgetype->id)->count());
            array_push($this->ctrIP, SGEStudent::where('type_id',$sgetype->id)->where('status',false)->count());
            array_push($this->ctrComplete, SGEStudent::where('type_id',$sgetype->id)->where('status',true)->count());
        }

    }

    public function updating()
    {
        $this->resetPage();
    }

    public function updated()
    {
        $this->resetPage();
    }

    public function render()
    {
        return view('livewire.dashboard');
    }
}

app/Http/Livewire/DepartmentTable.php
<?php

namespace App\Http\Livewire;

use App\Models\User;
use App\Models\Course;
use App\Models\Department;
use Livewire\Component;
use Livewire\WithPagination;

class DepartmentTable extends Component
{
    use WithPagination;

    protected $departments;
    public $search = null;
    public $users, $courses;

    public function mount(User $users, Course $courses)
    {
        $this->users = $users->where('role', 3)->get();
        $this->courses = $courses->all();
    }

    public function updating()
    {
        $this->resetPage();
    }

    public function updated()
    {
        $this->resetPage();
    }

    public function render()
    {
        $this->departments = is_null($this->search) || $this->search == '' ? Department::orderBy('name')->paginate(5) : Department::search($this->search)->orderBy('name')->paginate(5);
        return view('livewire.department-table', [
            'departments' => $this->departments,
        ]);
    }
}

app/Http/Livewire/ProgramTable.php
<?php

namespace App\Http\Livewire;

use App\Models\Course;
use App\Models\Department;
use Livewire\Component;
use Livewire\WithPagination;

class ProgramTable extends Component
{
    use WithPagination;

    protected $courses;
    public $search = null;
    public $department;

    public function updating()
    {
        $this->resetPage();
    }

    public function updated()
    {
        $this->resetPage();
    }

    public function render()
    {
        $this->courses = is_null($this->search) || $this->search == '' ? Course::where('department_id',$this->department->id)->paginate(5) : Course::search($this->search)->where('department_id',$this->department->id)->paginate(5);
        return view('livewire.program-table', [
            'courses' => $this->courses,
        ]);
    }
}

app/Http/Livewire/SGETable.php
<?php

namespace App\Http\Livewire;

use App\Models\SGETypes;
use Livewire\Component;
use Livewire\WithPagination;

class SGETable extends Component
{
    use WithPagination;

    protected $sge_types;
    public $search = null;

    public function updating()
    {
        $this->resetPage();
    }

    public function updated()
    {
        $this->resetPage();
    }

    public function render()
    {
        $this->sge_types = is_null($this->search) || $this->search == '' ? SGETypes::orderBy('name')->paginate(5) : SGETypes::search($this->search)->orderBy('name')->paginate(5);
        return view('livewire.s-g-e-table', [
            'sge_types' => $this->sge_types,
        ]);
    }
}

app/Http/Livewire/StudentClasslist.php
<?php

namespace App\Http\Livewire;

use App\Models\Course;
use App\Models\Student;
use App\Models\SGEStudent;
use Livewire\Component;
use Livewire\WithPagination;

class StudentClasslist extends Component
{
    use WithPagination;

    protected $students;
    public $sge_class;
    public $programs;
    public $search = null;

    public function mount($sge_class, Course $courses)
    {
        $this->sge_class = $sge_class;
        $this->programs = $courses->all();
    }

    public function updating()
    {
        $this->resetPage();
    }

    public function updated()
    {
        $this->resetPage();
    }

    public function render()
    {
        $this->students = is_null($this->search) || $this->search == '' ? SGEStudent::where('class_id',$this->sge_class->id)->orderBy('student_id')->paginate(8) : SGEStudent::where('class_id',$this->sge_class->id)->search($this->search)->orderBy('student_id')->paginate(8);
        return view('livewire.student-classlist', [
            'students' => $this->students,
        ]);
    }
}

app/Http/Livewire/StudentTable.php
<?php

namespace App\Http\Livewire;

use App\Models\Course;
use App\Models\Student;
use Livewire\Component;
use Livewire\WithPagination;

class StudentTable extends Component
{
    use WithPagination;

    protected $students;
    public $programs;
    public $search = null;

    public function mount(Course $courses)
    {
        $this->programs = $courses->all();
    }

    public function updating()
    {
        $this->resetPage();
    }

    public function updated()
    {
        $this->resetPage();
    }

    public function render()
    {
        $this->students = is_null($this->search) || $this->search == '' ? Student::orderBy('student_number')->paginate(8) : Student::search($this->search)->orderBy('student_number')->paginate(8);
        return view('livewire.student-table', [
            'students' => $this->students,
        ]);
    }
}

app/Http/Livewire/UserTable.php
<?php

namespace App\Http\Livewire;

use App\Models\User;
use Livewire\Component;
use Livewire\WithPagination;

class UserTable extends Component
{
    use WithPagination;

    protected $users;
    public $search = null;

    public function updating()
    {
        $this->resetPage();
    }

    public function updated()
    {
        $this->resetPage();
    }

    public function render()
    {
        $this->users = is_null($this->search) || $this->search == '' ? User::orderBy('role')->paginate(5) : User::search($this->search)->orderBy('role')->paginate(5);
        return view('livewire.user-table', [
            'users' => $this->users,
        ]);
    }
}

resources/views/livewire/classlist-table.blade.php
<div>
    <div class="flex flex-col items-center justify-center w-full h-full p-6">
        <div class="flex flex-row items-center justify-between w-full py-2 space-x-2 sm:px-6 lg:px-8">
            <input wire:model="search" class="w-full p-2 text-sm text-black placeholder-gray-500 border border-gray-200 rounded-md focus:border-amber-300/50 focus:ring-1 focus:ring-amber-300/50 focus:outline-none" type="text" placeholder="Search Classlist" />
            <a href="{{ route('sge_classes.create') }}" class="px-4 py-2 text-sm border border-gray-200 rounded-md text-amber-900 bg-amber-300 hover:bg-opacity-80 focus:border-amber-300/50 focus:ring-1 focus:ring-amber-300/50 focus:outline-none">
                <i class="fas fa-plus"></i>
            </a>
        </div>
    
        <div class="flex flex-col w-full sm:-mx-6 lg:-mx-8">
            <div class="-my-2 overflow-x-auto">
            <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
                <div class="overflow-hidden border-b border-gray-200 shadow sm:rounded-lg">
                <table class="w-full min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                    <tr>
                        <th scope="col" class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase">
                        Class Name
                        </th>
                        <th scope="col" class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase">
                        SGE Type
                        </th>
                        <th scope="col" class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase">
                        Participants
                        </th>
                        <th scope="col" class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase">
                        In Progress
                        </th>
                        <th scope="col" class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase">
                        Completed
                        </th>
                        <th scope="col" class="px-6 py-3 text-xs font-medium tracking-wider text-center text-gray-500 uppercase">
                        Options
                        </th>
                    </tr>
                    </thead>
                    <tbody class="bg-white divide-y divide-gray-200">
                    @foreach($sge_classes as $sge)
                    <tr>
                        <td class="px-6 py-4 text-sm text-left text-gray-500 uppercase whitespace-nowrap">
                            {{ $sge->name }}
                        </td>
                        <td class="px-6 py-4 text-sm text-left text-gray-500 whitespace-nowrap">
                            {{ $sge_types->where('id', $sge->type_id)->first()->name }}
                        </td>
                        <td class="px-6 py-4 text-sm text-left text-gray-500 whitespace-nowrap">
                            {{ $students->where('class_id',$sge->id)->count() }}
                        </td>
                        <td class="px-6 py-4 text-sm text-left text-gray-500 whitespace-nowrap">
                            {{ $students->where('class_id',$sge->id)->where('status',false)->count() }}
                        </td>
                        <td class="px-6 py-4 text-sm text-left text-gray-500 whitespace-nowrap">
                            {{ $students->where('class_id',$sge->id)->where('status',true)->count() }}
                        </td>
                        <td class="flex flex-row items-center justify-center px-6 py-4 space-x-2 text-sm font-medium text-center whitespace-nowrap">
                            <a href="{{ route('sge_classes.show',$sge->id) }}" class="text-center text-gray-600 hover:text-gray-900"><i class="fas fa-user"></i></a>
                            <a href="{{ route('sge_classes.edit',$sge->id) }}" class="text-center text-gray-600 hover:text-gray-900"><i class="fas fa-edit"></i></a>
                            <form id="del{{$sge->id}}" method="POST" action="{{ route('sge_classes.destroy',$sge->id) }}">
                                @method('delete')
                                @csrf
                                <button type="submit" class="text-center text-red-600 hover:text-red-900 focus:outline-none" onclick="delConfirm('del{{$sge->id}}')"><i class="fas fa-trash"></i></button>
                            </form>
                            <a href="{{ route('students.export',$sge->id) }}" class="text-center text-gray-600 hover:text-gray-900"><i class="fas fa-print"></i></a>
                        </td>
                    </tr>
                    @endforeach
                    </tbody>
                </table>
                </div>
            </div>
            </div>
        </div> 
        <div class="w-full py-2 sm:px-6 lg:px-8">
            {{ $sge_classes->links() }}
        </div>
    </div>
</div>

<script language="javascript" type="text/javascript">
    function delConfirm(paramID) {
        if(confirm('Are you sure you want to delete this data?')) {
            document.getElementById(paramID).submit();
        }
    }
</script>

resources/views/livewire/dashboard.blade.php
<div>
    <div class="grid grid-cols-1 gap-6 md:grid-cols-3">
        <div class="flex flex-row items-center justify-center w-auto h-20 p-4 text-xl font-extrabold text-white uppercase bg-red-500 border-4 border-yellow-300 md:h-auto rounded-xl">
            <p><i class="px-2 fas fa-users"></i> STUDENTS: </p>
            <p class="px-2">{{$total_students->count()}}</p>
        </div>
        <div class="flex flex-row items-center justify-center w-auto h-20 p-4 text-xl font-extrabold text-white uppercase bg-green-500 border-4 border-yellow-300 md:h-auto rounded-xl">
            <p><i class="px-2 fas fa-building"></i>DEPARTMENTS: </p>
            <p class="px-2">{{$departments->count()}}</p>
        </div>
        <div class="flex flex-row items-center justify-center w-auto h-20 p-4 text-xl font-extrabold text-white uppercase bg-blue-500 border-4 border-yellow-300 md:h-auto rounded-xl">
            <p><i class="px-2 fas fa-book"></i> CLASSLIST: </p>
            <p class="px-2">{{$classlists->count()}}</p>
        </div>
    </div>
    <div class="grid grid-cols-1 gap-6 py-2 md:grid-cols-2">
        <div class="flex flex-col items-center justify-center w-auto h-full p-4 text-xl font-extrabold text-white uppercase border-4 border-yellow-300 rounded-xl">
            <canvas id="myChart1" class="w-full h-full"></canvas>
            <script>
                const sgetypes = <?php echo json_encode($sgetypes); ?>;
                const ctrStudentsPerType = <?php echo json_encode($ctrStudentsPerType); ?>;

                var lblsgetypes = [];
                var clrsgetypes = [];
                var bdrsgetypes = [];

                sgetypes.forEach(SGETypes);

                function SGETypes(item, index) {
                    lblsgetypes.push(item['name']);
                    clrsgetypes.push('rgba('+ColorGen()+','+ColorGen()+','+ColorGen()+', 0.2)');
                    bdrsgetypes.push('rgba('+ColorGen()+','+ColorGen()+','+ColorGen()+', 1)');
                }
                    
                function ColorGen() {
                    return Math.floor((Math.random() * 255));
                }

                const ctx = document.getElementById('myChart1').getContext('2d');
                const myChart1 = new Chart(ctx, {
                    type: 'pie',
                    data: {
                        labels: lblsgetypes,
                        datasets: [{
                            label: 'STUDENTS PER SGE TYPES',
                            data: ctrStudentsPerType,
                            backgroundColor: clrsgetypes,
                            borderColor: bdrsgetypes,
                            borderWidth: 1
                        }]
                    },
                    options: {
                        scales: {
                            y: {
                                beginAtZero: true
                            }
                        }
                    }
                });
            </script>
        </div>
        <div class="flex flex-col items-center justify-center w-auto h-full p-4 text-xl font-extrabold text-white uppercase border-4 border-yellow-300 rounded-xl">
            <canvas id="myChart2" class="w-full h-full"></canvas>
            <script>
            const ctrIP = <?php echo json_encode($ctrIP); ?>;
            const ctrComplete = <?php echo json_encode($ctrComplete); ?>;
            const ctx1 = document.getElementById('myChart2').getContext('2d');
            const myChart2 = new Chart(ctx1, {
                type: 'line',
                data: {
                    labels: lblsgetypes,
                    datasets: [{
                        label: 'In Progress',
                        data: ctrIP,
                        backgroundColor: [
                            'rgba(255, 99, 132, 0.2)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(255, 206, 86, 0.2)',
                            'rgba(75, 192, 192, 0.2)',
                            'rgba(153, 102, 255, 0.2)',
                            'rgba(255, 159, 64, 0.2)'
                        ],
                        borderColor: [
                            'rgba(255, 99, 132, 1)',
                            'rgba(54, 162, 235, 1)',
                            'rgba(255, 206, 86, 1)',
                            'rgba(75, 192, 192, 1)',
                            'rgba(153, 102, 255, 1)',
                            'rgba(255, 159, 64, 1)'
                        ],
                        borderWidth: 1
                    },
                    {
                        label: 'Completed',
                        data: ctrComplete,
                        backgroundColor: [
                            'rgba(255, 99, 132, 0.2)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(255, 206, 86, 0.2)',
                            'rgba(75, 192, 192, 0.2)',
                            'rgba(153, 102, 255, 0.2)',
                            'rgba(255, 159, 64, 0.2)'
                        ],
                        borderColor: [
                            'rgba(255, 99, 132, 1)',
                            'rgba(54, 162, 235, 1)',
                            'rgba(255, 206, 86, 1)',
                            'rgba(75, 192, 192, 1)',
                            'rgba(153, 102, 255, 1)',
                            'rgba(255, 159, 64, 1)'
                        ],
                        borderWidth: 1
                    }
                    ]
                },
                options: {
                    scales: {
                        y: {
                            beginAtZero: true
                        }
                    }
                }
            });
            </script>
        </div>
    </div>
</div>

resources/views/livewire/department-table.blade.php
<div>            
    <div class="flex flex-col items-center justify-center w-full h-full p-6">
        <div class="flex flex-row items-center justify-between w-full py-2 space-x-2 sm:px-6 lg:px-8">
            <input wire:model="search" class="w-full p-2 text-sm text-black placeholder-gray-500 border border-gray-200 rounded-md focus:border-amber-300/50 focus:ring-1 focus:ring-amber-300/50 focus:outline-none" type="text" placeholder="Search Departments" />
            <a href="{{ route('departments.create') }}" class="px-4 py-2 text-sm border border-gray-200 rounded-md text-amber-900 bg-amber-300 hover:bg-opacity-80 focus:border-amber-300/50 focus:ring-1 focus:ring-amber-300/50 focus:outline-none">
                <i class="fas fa-plus"></i>
            </a>
        </div>
    
        <div class="flex flex-col w-full sm:-mx-6 lg:-mx-8">
            <div class="-my-2 overflow-x-auto">
            <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
                <div class="overflow-hidden border-b border-gray-200 shadow sm:rounded-lg">
                <table class="w-full min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                    <tr>
                        <th scope="col" class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase">
                        School/Department
                        </th>
                        <th scope="col" class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase">
                        Dean
                        </th>
                        <th scope="col" class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase">
                        Programs
                        </th>
                        <th scope="col" class="px-6 py-3 text-xs font-medium tracking-wider text-center text-gray-500 uppercase">
                        Options
                        </th>
                    </tr>
                    </thead>
                    <tbody class="bg-white divide-y divide-gray-200">
                    @foreach($departments as $department)
                    <tr>
                        <td class="px-6 py-4 text-sm text-left text-gray-500 whitespace-nowrap">
                            {{ $department->name }}
                        </td>
                        <td class="px-6 py-4 text-sm text-left text-gray-500 whitespace-nowrap">
                            {{ $users->where('id', $department->dean_id)->first()->name }}
                        </td>
                        <td class="px-6 py-4 text-sm text-left text-gray-500 whitespace-nowrap">
                            {{ $courses->where('department_id',$department->id)->count() }}
                        </td>
                        <td class="flex flex-row items-center justify-center px-6 py-4 space-x-2 text-sm font-medium text-center whitespace-nowrap">
                            <a href="{{ route('programs.show',$department->id) }}" class="text-center text-gray-600 hover:text-gray-900"><i class="fas fa-book"></i></a>
                            <a href="{{ route('departments.edit',$department->id) }}" class="text-center text-gray-600 hover:text-gray-900"><i class="fas fa-edit"></i></a>
                            <form id="del{{$department->id}}" method="POST" action="{{ route('departments.destroy',$department->id) }}">
                                @method('delete')
                                @csrf
                                <button type="button" class="text-center text-red-600 hover:text-red-900 focus:outline-none" onclick="delConfirm('del{{$department->id}}')"><i class="fas fa-trash"></i></button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                    </tbody>
                </table>
                </div>
            </div>
            </div>
        </div> 
        <div class="w-full py-2 sm:px-6 lg:px-8">
            {{ $departments->links() }}
        </div>
    </div>
</div>

<script language="javascript" type="text/javascript">
    function delConfirm(paramID) {
        if(confirm('Are you sure you want to delete this data?')) {
            document.getElementById(paramID).submit();
        }
    }
</script>

resources/views/livewire/user-table.blade.php
<div>
    <div class="flex flex-col items-center justify-center p-6 py-6 border-4 shadow-xl bg-white/90 border-amber-300/50 sm:rounded-lg">
                
        <div class="flex flex-row items-center justify-between w-full py-2 space-x-2 sm:px-6 lg:px-8">
            <input wire:model="search" class="w-full p-2 text-sm text-black placeholder-gray-500 border border-gray-200 rounded-md focus:border-amber-300/50 focus:ring-1 focus:ring-amber-300/50 focus:outline-none" type="text" placeholder="Search Users" />
            <a href="{{ route('users.create') }}" class="px-4 py-2 text-sm border border-gray-200 rounded-md text-amber-900 bg-amber-300 hover:bg-opacity-80 focus:border-amber-300/50 focus:ring-1 focus:ring-amber-300/50 focus:outline-none">
                <i class="fas fa-user-plus"></i>
            </a>
        </div>

        <div class="flex flex-col w-full sm:-mx-6 lg:-mx-8">
            <div class="-my-2 overflow-x-auto">
            <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
                <div class="overflow-hidden border-b border-gray-200 shadow sm:rounded-lg">
                <table class="w-full min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                    <tr>
                        <th scope="col" class="px-6 py-3 text-xs font-medium tracking-wider text-center text-gray-500 uppercase">
                        Name
                        </th>
                        <th scope="col" class="px-6 py-3 text-xs font-medium tracking-wider text-center text-gray-500 uppercase">
                        Role
                        </th>
                        <th scope="col" class="px-6 py-3 text-xs font-medium tracking-wider text-center text-gray-500 uppercase">
                        Options
                        </th>
                    </tr>
                    </thead>
                    <tbody class="bg-white divide-y divide-gray-200">
                    @foreach($users as $user)
                    <tr>
                        <td class="px-6 py-4 whitespace-nowrap">
                        <div class="flex items-center">
                            <div class="flex-shrink-0 w-10 h-10">
                            <img class="w-10 h-10 rounded-full" src="{{ $user->profile_photo_url }}" alt="">
                            </div>
                            <div class="ml-4">
                            <div class="text-sm font-medium text-gray-900 capitalize">
                                {{ $user->name }}
                            </div>
                            <div class="text-sm text-gray-500">
                                {{ $user->email }}
                            </div>
                            </div>
                        </div>
                        </td>
                        <td class="px-6 py-4 text-sm text-center text-gray-500 whitespace-nowrap">
                        {{ $user->role == 0 ? 'ADMIN' : ($user->role == 1 ? 'ICEP Director' : ($user->role == 2 ? 'ILRAD Director' : ($user->role == 3 ? 'Dean' : 'Staff' ) ) ) }}
                        </td>
                        <td class="flex flex-row items-center justify-center px-6 py-4 space-x-2 text-sm font-medium text-center whitespace-nowrap">
                            <a href="{{ route('users.edit',$user->id) }}" class="text-center text-gray-600 hover:text-gray-900"><i class="fas fa-edit"></i></a>
                            <form id="del{{$user->id}}" method="POST" action="{{ route('users.destroy',$user->id) }}">
                                @method('delete')
                                @csrf
                                <button type="button" class="text-center text-red-600 hover:text-red-900 focus:outline-none" onclick="delConfirm('del{{$user->id}}')"><i class="fas fa-trash"></i></button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                    </tbody>
                </table>
                </div>
            </div>
            </div>
        </div> 
        <div class="w-full py-2 sm:px-6 lg:px-8">
            {{ $users->links() }}
        </div>
    </div>
</div>

<script language="javascript" type="text/javascript">
    function delConfirm(paramID) {
        if(confirm('Are you sure you want to delete this data?')) {
            document.getElementById(paramID).submit();
        }
    }
</script>